파이썬 행렬 헷갈리는거... 

리스트를 행렬로 바꿨을 때 shape에서 (n,)이렇게 나오는 것과
[:] 이것

In [ ]:
import numpy as np

In [37]:
b = list([1, 2, 3, 4])

In [45]:
c = np.array(b)

In [39]:
print(c)

[1 2 3 4]


In [40]:
print(c.shape)

(4,)


행렬의 shape가 (4,)일 때의 결과값.
이제 reshape로 정상적인? 행렬 형으로 바꿔본다.

In [ ]:
c = c.reshape(4, -1) #-1은 가변인자라고 알고 있음.

In [43]:
print(c, c.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)


In [44]:
c = np.transpose(c)
print(c, c.shape)

[[1 2 3 4]] (1, 4)


In [46]:
c = c.reshape(-1, 4)

In [47]:
print(c, c.shape)

[[1 2 3 4]] (1, 4)


(1, 4)이든 (4, 1)이든 (4,)일때와 같은 결과값은 없다.

(4,)일때는 행렬이기는 한데... 약간 저기서 받은 리스트를 행으로 넣어야 할지 열로 넣어야 할지 정하지 못한 단계라고 생각하면 될 것 같다.

리스트를 행렬로 바꿔줄 때나, 혹시 행렬의 shape가 (n,)이 꼴이라면 reshape로 바꿔주어야 하는 것 같다.

이제 밑에는 [:,:]이랑 [숫자,:] 차이... 당연히 차이가 있겠지만 자꾸 별 생각없이 :를 써서 기억하려고 다시 쓴다.



In [9]:
d = list([11, 12, 13, 14])

In [26]:
e = np.array([b, d])

In [27]:
e

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [28]:
e.shape

(2, 4)

In [29]:
print(e[:,:])

[[ 1  2  3  4]
 [11 12 13 14]]


In [30]:
print(e[:,2])

[ 3 13]


In [31]:
print(e[1,:])

[11 12 13 14]


In [32]:
print(e[1,2])

13


[:,:]일 때는 행렬의 값을 전부 가져오고

e[:,2]일 떄는 뒤의 index를 2로 고정시키고 앞의 것을 전부 다 반복해서 값을 가져온다.

e[1,:]이면 앞의 index를 1로 고정하고 뒤에 뺑뺑이.

:랑 for문이랑 비슷하다고 생각하면 될 것 같다. 이제 안헷갈리겠지.